### ISSUE TITLE
Scroll bar present on home page

### ISSUE THREAD

**Issue by GFernie** [Group-A/Twitter-Analysis-World-Map#23]
Vertical scroll bar is showing on page.
Disappears when options menu is opened.

Probably CSS issue.

**Comment by ghost** [comment]
Believe 000d2c739441e42f5e147fd340e54d41ac0819f5 resolves this

**Comment by GFernie** [comment]
Scroll bar still appears after opening and closing a modal box.

![image](https://cloud.githubusercontent.com/assets/9322279/6738410/c88af296-ce69-11e4-8dba-b5e803bda1d7.png)

![image](https://cloud.githubusercontent.com/assets/9322279/6738419/d6897188-ce69-11e4-945f-ce72a445396d.png)

![image](https://cloud.githubusercontent.com/assets/9322279/6738429/e5801228-ce69-11e4-925e-6cfcc909a7c8.png)
